# config data for create_cmaq_csv.py application

cmaq2011:
    netcdf-path: /Users/${USER}/CMAQ/2011/  # must end with /
    netcdf-file-name: CCTM_CMAQ_v51_Release_Oct23_NoDust_ed_emis_combine.aconc.01
    out-csv-path: /Users/${USER}/CMAQ/2011/  # must end with /
    out-csv-file-name: cmaq2011.csv
    data-vars: # enter data vars of interest in CMAQ 2011 netCDF files
       - O3
       - PMIJ
